## ApacheTika API Calls
## Author: Praveen Chamarthi
@hostname = localhost
@port = 9998
@host = {{hostname}}:{{port}}
@contentType = application/json

@indexname = sooperindex

### Touch Tika Server
# curl -X GET http://{{host}}/tika

PUT http://{{host}}/tika 
Content-Type: application/pdf



curl -T price.xls http://{{host}}/tika --header "Accept: text/html"
curl -T price.xls http://{{host}}/tika --header "Accept: text/plain"