## Elasticsearch API Calls
## Author: Praveen Chamarthi
@hostname = localhost
@port = 9200
@host = {{hostname}}:{{port}}
@contentType = application/json
@indexname = knowledgeindex


### Get Indices
GET http://localhost:9200/_cat/indices?v

### Create Index
### Create Index , Add n-gram Analyzer to index
PUT http://{{host}}/etaa
Content-Type: {{contentType}}

{
    "settings": {
        "number_of_shards": 1,
        "number_of_replicas": 0
    }
}


PUT http://{{host}}/{{indexname}}
Content-Type: {{contentType}}

{
    "settings": {
        "number_of_shards": 1,
        "number_of_replicas": 2,
        "analysis": {
            "filter": {
                "autocomplete_filter": {
                    "type": "edge_ngram",
                    "min_gram": 1,
                    "max_gram": 20
                }
            },
            "analyzer":{
                "autocomplete": {
                    "type": "custom",
                    "tokenizer": "standard",
                    "filter": [
                        "lowercase",
                        "autocomplete_filter"
                    ]
                }
            }
        }
    },
    "mappings": {
        "properties": {
            "title": {"type": "text" },
            "description": {"type": "text" },
            "author": {"type": "text" },
            "creation_date": {"type": "date" },
            "content_type": {"type": "text" },
            "keywords": {"type": "text" },
            "num_pages": {"type": "integer" },
            "filename":  {"type": "text" },
            "content":  {"type": "text" }
        }
    }
}


### Get Index
GET http://{{host}}/{{indexname}}
Content-Type: {{contentType}}

### Get Index Mapping
GET http://{{host}}/{{indexname}}/_mappings
Content-Type: {{contentType}}


### Search Index
GET http://{{host}}/{{indexname}}/_search
Content-Type: {{contentType}}

{
    "query" : {
        "term" : { "title" : "primal" }
    }
}

### Delete Index
DELETE http://{{host}}/{{indexname}}


### Queries
@queryText = "aurora"
curl "http://localhost:9200/{{indexname}}/_search?q={{queryText}}&_source=*title,*description&pretty"